FROM node:14.17.0-alpine as build-stage

WORKDIR /app
COPY package*.json ./
# RUN npm install -g npm@7.18.1
RUN npm ci

COPY ./ .

ENV NODE_ENV=production
RUN npm run build

FROM nginx:stable-alpine as production-stage

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf